services:
  backend:
    build: .
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8083:8083"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://host.docker.internal:3306/pixeldb?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=rgardelserver75
      - SERVER_PORT=8083

  frontend:
    build: ./frontend-demo
    ports:
      - "8888:80"
    depends_on:
      - backend
    # Note: frontend nginx.conf needs to point to localhost:8083
