services:
  backend:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://host.docker.internal:3306/pixeldb?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=rgardelserver75
    extra_hosts:
      - "host.docker.internal:host-gateway"

  frontend:
    build: ./frontend-demo
    ports:
      - "80:80"
    depends_on:
      - backend
